### ISSUE TITLE
Update field CSS

### ISSUE THREAD

**Issue by MrJamesEllis** [silverstripe-australia/silverstripe-multivaluefield#105]
### Description

I've opened #104 to look at updating the field CSS and bring it into line with other fields used in the administration area.

See PR for more. I opened it against the "5" branch, it's a pretty simple change that could be cherry-picked into other branches, once it's OK'd

### Validations

- [X] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

## PRs
- https://github.com/symbiote/silverstripe-multivaluefield/pull/104

**Comment by GuySartorelli** [comment]
The associated PR has been closed.
