### ISSUE TITLE
CSS and JS files not found after Silverstripe 5 upgrade

### ISSUE THREAD

**Issue by jesscostello** [silverstripe-australia/silverstripe-multivaluefield#117]
### Module version(s) affected

6.1

### Description

I am upgrading one of my sites from silverstripe 4 to 5.2 and I am using https://github.com/nswdpc/silverstripe-csp which is pulling in version 6.1 of this module. When I try to access the page in the CMS which is using the multivalue fields I get the following errors.

```
error-log.NOTICE: E_USER_NOTICE: File vendor/symbiote/silverstripe-multivaluefield/client/dist/js/multivaluefield.js does not exist {"code":1024,"message":"File vendor/symbiote/silverstripe-multivaluefield/client/dist/js/multivaluefield.js does not exist","file":"/var/www/html/vendor/silverstripe/framework/src/Control/SimpleResourceURLGenerator.php","line":84} []
error-log.NOTICE: E_USER_NOTICE: File vendor/symbiote/silverstripe-multivaluefield/client/dist/styles/multivaluefield.css does not exist {"code":1024,"message":"File vendor/symbiote/silverstripe-multivaluefield/client/dist/styles/multivaluefield.css does not exist","file":"/var/www/html/vendor/silverstripe/framework/src/Control/SimpleResourceURLGenerator.php","line":84} []

```

### How to reproduce

I have tried running `composer vendor-expose`, flushing the cache and removing and reinstalling all my composer modules. There doesn't seem to be any js/css issues with any of the other modules. I also tried `composer vendor-expose copy` but I got this error 

```
Exposing web directories for silverstripe-vendormodule symbiote/silverstripe-multivaluefield with method copy:
  - client/dist

In Filesystem.php line 370:

  copy(/var/www/html/vendor/symbiote/silverstripe-multivaluefield/client/dist): Failed to open stream: No such file or directory


vendor-expose [<method>]
```

**Comment by GuySartorelli** [comment]
I can't reproduce this.
I have seen a few people say they had similar problems in the last week or so and it resolved itself... can you please try again and let me know if it's still a problem?

**Comment by jesscostello** [comment]
Thanks for following up, I had the same situation.. it resolved itself later that day after making no changes at all! 🤯

**Comment by matt-in-a-hat** [comment]
I've also run into this error - looking at the state on disk:
`vendor/symbiote/silverstripe-multivaluefield/client/dist -> ../../../../../../vendor/symbiote/silverstripe-multivaluefield/client/dist`
This folder within the vendor module seems to just be a smylink?

This makes sense in public/_resources:
`public/_resources/vendor/symbiote/silverstripe-multivaluefield/client/dist -> ../../../../../../vendor/symbiote/silverstripe-multivaluefield/client/dist`

But somehow there's no actual dist content in the module.
Could this be some weird bug with updating this module from an old version?

**Comment by matt-in-a-hat** [comment]
Can confirm that removing and reinstalling this module fixes the issue (well, csp module in my case).
