### ISSUE TITLE
Html entities get re-escaped

### ISSUE THREAD

**Issue by jkempff** [silverstripe-australia/silverstripe-multivaluefield#19]
Using the KeyValueField, I noticed, if the Key or Value of a MultiValueField contains an ampersand (or some quotes), they become html entities.
However, when reloading the Field, you see those HTML entities:

Value `Example "Value"` becomes `Example &quot;Value&quot;`. So far, this may be a usability problem.

But when re-saving, it becomes an endless loop: *all ampersands* get parsed again and the value becomes `Example &amp;quot;Value&amp;quot;`.

I havent yet checked MultiValueTextField, DropdownField or CheckboxField.

**Comment by nyeholt** [comment]
Thanks! Was an issue in just the KeyValueField itself, have pushed a fix for it.
