### ISSUE TITLE
PHP 7.4 - Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by extravio** [silverstripe-australia/silverstripe-multivaluefield#69]
On PHP 7.4, the following warning appears:

Deprecated: Array and string offset access syntax with curly braces is deprecated in .../vendor/symbiote/silverstripe-multivaluefield/src/ORM/FieldType/MultiValueField.php on line 104

**Comment by extravio** [comment]
Just realized it has been fixed on branch 5.
Not available in the latest tagged version (5.0.1)

**Comment by mikeyc7m** [comment]
how do we get this fix via composer?

**Comment by mikeyc7m** [comment]
i was able to get via composer using 5.0.x-dev
