### ISSUE TITLE
jquery no longer available

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe-australia/silverstripe-multivaluefield#89]
IN the latest versions of silverstripe/admin, jquery is no longer in thirdparty/jquery folder.  I would suggest you include
```
https://code.jquery.com/jquery-3.3.1.min.js
```
instead,  something like that? Of course, the best course of action is to merge it all into a `dist/app.js` file. 

## PRs
- https://github.com/symbiote/silverstripe-multivaluefield/pull/90

**Comment by GuySartorelli** [comment]
Looks like you've raised a PR to fix this: https://github.com/symbiote/silverstripe-multivaluefield/pull/90
Please remember to link the PR to the issue and vice versa, it helps a lot keeping track of what kind of work is required (review existing PR vs fix it ourselves)
Also: Thank you for both reporting this and raising a PR to fix it! That's awesome.

**Comment by GuySartorelli** [comment]
PR has been merged. This will be automatically tagged by GitHub Actions.
